### ISSUE TITLE
How to access KeyboardOptions interface?

### ISSUE THREAD

**Issue by xinthose** [hodgef/simple-keyboard#865]
We import simple keyboard like this: `import Keyboard from "simple-keyboard"` instead of like this: `import { Keyboard } from "simple-keyboard"` because of this line: https://github.com/hodgef/simple-keyboard/blob/852d3049efc31f766f71af11f0715cd4235b39ea/src/lib/%40types/index.d.ts#L328

What I would like to do is install `@types/simple-keyboard` (but I know that this does not exist according to PR #40) and import `KeyboardOptions` like this: `import { Keyboard, KeyboardOptions } from "simple-keyboard";`.  

How can I access the `KeyboardOptions` interface without installing types in Angular 10?

**Comment by hodgef** [comment]
Hello @xinthose,

This should be fixed as of the latest release. Please feel free to update to simple-keyboard@2.32.77.

You can then access `KeyboardOptions` like so:
```
import Keyboard, { KeyboardOptions } from "simple-keyboard";
```

Regards,
Francisco Hodge

**Comment by xinthose** [comment]
@hodgef Thank you for your help.  When I try this line in my code `import { Keyboard } from "simple-keyboard";` after running `npm update` and getting `+ simple-keyboard@2.32.78`, I still get this error in VisualStudio Code:

> Module '"simple-keyboard"' has no exported member 'Keyboard'. Did you mean to use 'import Keyboard from "simple-keyboard"' instead?ts(2614)

**Comment by hodgef** [comment]
Hello @xinthose,

Per the example above, the correct statement is:
```
import Keyboard, { KeyboardOptions } from "simple-keyboard";
```

Regards,
Francisco Hodge

**Comment by xinthose** [comment]
@hodgef ah, I see.  Did not know you could import like that (first time seeing it).  It is working for me.  Thank you for your help sir.

**Comment by dikaso** [comment]
it seems that this does not work anymore:

```ts
import { KeyboardOptions } from "simple-keyboard";
```

It gives:

`Module '"simple-keyboard"' has no exported member 'KeyboardOptions'. Did you mean to use 'import KeyboardOptions from "simple-keyboard"' instead?`

**Comment by hodgef** [comment]
Thanks for reporting this @dikaso, it should be fixed as of version 3.6.39 (latest). Feel free to give it a try.

Regards,
Francisco Hodge

**Comment by dikaso** [comment]
That was fast. It works now.
